version: "3.5"

services:

  postgres:
    image: postgres:10
    volumes:
      - "/tmp/metabase/db_data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  metabase:
    depends_on:
      - postgres
    image: metabase/metabase
    ports:
      - "3000:3000"
    restart: always
    environment:
      MB_ENCRYPTION_SECRET_KEY: ${MB}
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres

  # pgadmin:
  #   depends_on:
  #     - postgres
  #   image: dpage/pgadmin4
  #   ports:
  #     - "3001:80"
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: mail@example.com
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
