version: "3.5"

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - '3306'
    networks:
      - metabasenet

  metabase:
    depends_on:
      - mysql
    image: metabase/metabase
    expose:
      - '3000'
    restart: always
    environment:
      MB_DB_TYPE: mysql
      MB_DB_HOST: mysql
      MB_DB_DBNAME: ${MYSQL_DATABASE}
      MB_DB_PORT: 3306
      MB_DB_USER: ${MYSQL_USER}
      MB_DB_PASS: ${MYSQL_PASSWORD}
      JAVA_OPTS:  ${JAVA_OPTS}
    networks:
      - metabasenet

  nginx:
    depends_on:
      - mysql
      - metabase
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - '80:80'
      - '443:443'
    networks:
      - metabasenet


networks:
  metabasenet:
    driver: bridge
