version: "3.5"

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - '3306'
    networks:
      - metabasenet

  metabase:
    depends_on:
      - mysql
    image: metabase/metabase
    ports:
      - '3000:3000'
    restart: always
    environment:
      MB_DB_TYPE: mysql
      MB_DB_HOST: mysql
      MB_DB_DBNAME: ${MYSQL_DATABASE}
      MB_DB_PORT: 3306
      MB_DB_USER: ${MYSQL_USER}
      MB_DB_PASS: ${MYSQL_PASSWORD}
      JAVA_OPTS:  ${JAVA_OPTS}
    networks:
      - metabasenet

networks:
  metabasenet:
    driver: bridge
